/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.system_transaction.payment.multy_payment;

import core.Locals;
import javax.swing.JOptionPane;
import mainApp.findwindow.GUIFindWindow;
import system.accounts.AccountType;
import system.accounts.transaction.cheque.OBJCheque;

/**
 *
 * @author RoWi
 */
public class ChequePanle extends javax.swing.JDialog {

    /**
     * Creates new form ChequePnale
     */
    public ChequePanle(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    ChequePanle(Object object, boolean b, String voucherType) {
        this(null, b);
        this.voucherType = voucherType;
        initOthers();
    }

    private void doAdd() {
        if (checkFields() && Double.parseDouble(txtAmount.getText()) > 0.00) {
            OBJCheque cheque = new OBJCheque();
            cheque.setChqeNo(txtChequeNo.getText());
            cheque.setRDate(Locals.setDateFormat(txtRealizeDate.getDate()));
            cheque.setBank(txtBankCode.getText());
            cheque.setBankAccount(txtBankAccount.getText());
            cheque.setAmount(txtAmount.getText());
            cheque.setRemarks(txtRemark.getText());

            MultiPayOption.cheque = cheque;

            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "One or more required filds are empty");
        }
    }

    private boolean checkFields() {
        return !txtChequeNo.getText().isEmpty() && txtRealizeDate.getDate() != null && !txtBankCode.getText().isEmpty() && !txtAmount.getText().isEmpty();
    }

    private void getBank() {

        new GUIFindWindow(null, true, "Bank", "BankCode", "BankName").setVisible(true);
        String code = accountpackage.AccountPackage.CODE;
        String name = accountpackage.AccountPackage.NAME;
        txtBankCode.setText(code);
        txtBank.setText(name);
        accountpackage.AccountPackage.CODE = "";
        accountpackage.AccountPackage.NAME = "";
    }

    private void getBankAccount() {

        switch (voucherType) {
            case VoucherType.VOUCHER:
                new GUIFindWindow(null, true, "account", "AccCode", "AccName", "type", AccountType.BANK_ACCOUNT).setVisible(true);
                break;
            case VoucherType.GRN:
                new GUIFindWindow(null, true, "account", "AccCode", "AccName", "type", AccountType.BANK_ACCOUNT).setVisible(true);
                break;
        }

        String code = accountpackage.AccountPackage.CODE;
        String name = accountpackage.AccountPackage.NAME;
        txtBankAccount.setText(code);
        txtBankAccountName.setText(name);
        accountpackage.AccountPackage.CODE = "";
        accountpackage.AccountPackage.NAME = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initOthers() {
        switch (voucherType) {
            case VoucherType.VOUCHER:
                txtBankAccount.setEnabled(true);
                cmdBankAccount.setEnabled(true);
                break;
            case VoucherType.GRN:
                txtBankAccount.setEnabled(true);
                cmdBankAccount.setEnabled(true);
                break;
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtChequeNo = new javax.swing.JTextField();
        txtRemark = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtAmount = new javax.swing.JFormattedTextField();
        txtRealizeDate = new com.toedter.calendar.JDateChooser();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        cmdBank = new javax.swing.JButton();
        txtBank = new javax.swing.JTextField();
        txtBankCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        cmdBankAccount = new javax.swing.JButton();
        txtBankAccountName = new javax.swing.JTextField();
        txtBankAccount = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Cheque ");
        setMaximumSize(new java.awt.Dimension(305, 175));
        setMinimumSize(new java.awt.Dimension(305, 175));
        setResizable(false);

        jLabel1.setText("Cheque No");

        jLabel2.setText("Realize Date");

        jLabel3.setText("Bank");

        jLabel4.setText("Amount");

        jLabel5.setText("Remark");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        txtRealizeDate.setDateFormatString("yyyy-MM-dd");

        cmdBank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tool bar/help.png"))); // NOI18N
        cmdBank.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdBank.setContentAreaFilled(false);
        cmdBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBankActionPerformed(evt);
            }
        });
        jLayeredPane3.add(cmdBank);
        cmdBank.setBounds(70, 0, 21, 20);

        txtBank.setEditable(false);
        txtBank.setBackground(new java.awt.Color(255, 255, 241));
        jLayeredPane3.add(txtBank);
        txtBank.setBounds(95, 0, 160, 20);

        txtBankCode.setBackground(new java.awt.Color(255, 255, 241));
        txtBankCode.setDisabledTextColor(new java.awt.Color(153, 0, 0));
        jLayeredPane3.add(txtBankCode);
        txtBankCode.setBounds(0, 0, 70, 20);

        jLabel6.setText("Account");

        cmdBankAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tool bar/help.png"))); // NOI18N
        cmdBankAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdBankAccount.setContentAreaFilled(false);
        cmdBankAccount.setEnabled(false);
        cmdBankAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBankAccountActionPerformed(evt);
            }
        });
        jLayeredPane4.add(cmdBankAccount);
        cmdBankAccount.setBounds(70, 0, 21, 20);

        txtBankAccountName.setEditable(false);
        txtBankAccountName.setBackground(new java.awt.Color(255, 255, 241));
        txtBankAccountName.setEnabled(false);
        jLayeredPane4.add(txtBankAccountName);
        txtBankAccountName.setBounds(95, 0, 160, 20);

        txtBankAccount.setBackground(new java.awt.Color(255, 255, 241));
        txtBankAccount.setDisabledTextColor(new java.awt.Color(153, 0, 0));
        txtBankAccount.setEnabled(false);
        jLayeredPane4.add(txtBankAccount);
        txtBankAccount.setBounds(0, 0, 70, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChequeNo)
                            .addComponent(txtRealizeDate, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jLayeredPane3)
                    .addComponent(jLayeredPane4)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRemark)
                            .addComponent(txtAmount)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChequeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(txtRealizeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        doAdd();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmdBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBankActionPerformed
        getBank();
    }//GEN-LAST:event_cmdBankActionPerformed

    private void cmdBankAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBankAccountActionPerformed
        getBankAccount();
    }//GEN-LAST:event_cmdBankAccountActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBank;
    private javax.swing.JButton cmdBankAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JFormattedTextField txtAmount;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtBankAccount;
    private javax.swing.JTextField txtBankAccountName;
    private javax.swing.JTextField txtBankCode;
    private javax.swing.JTextField txtChequeNo;
    private com.toedter.calendar.JDateChooser txtRealizeDate;
    private javax.swing.JTextField txtRemark;
    // End of variables declaration//GEN-END:variables
private String voucherType;
}
