/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.reminder;

import core.reminder.object.LowStockItem;
import core.reminder.object.UpcomingCheque;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RoWi
 */
public class GUIReminder extends javax.swing.JInternalFrame {

    private static GUIReminder reminder;
    /**
     * Creates new form GUIReminder
     */
    private GUIReminder() {

        initComponents();
        initOthers();

    }

    public static GUIReminder getGUIReminder() {
        if (reminder == null) {
            reminder = new GUIReminder();
        }
        return reminder;
    }

    private void loadVoucherRealization() {
        upcomingVoucherCheques = new ArrayList<>();
        upcomingVoucherCheques = SERReminder.voucherRealization();
        DefaultTableModel dt = (DefaultTableModel) tblVoucherRealization.getModel();
        int i = 0;
        for (UpcomingCheque upcomingCheque : upcomingVoucherCheques) {
            dt.addRow(new Object[]{upcomingCheque.getCustomer(), upcomingCheque.getBank(), upcomingCheque.getDate(), upcomingCheque.getChequeNo(), upcomingCheque.getAmount()});
            i++;
        }
        for (int j = i; j < 13; j++) {
            dt.addRow(new Object[]{"", "", "", "", ""});

        }
//        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
//        rightRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
//        tblVoucherRealization.getColumnModel().getColumn(3).setCellRenderer(rightRenderer);

        tblVoucherRealization.setDefaultRenderer(Object.class, new ReminderCellRender());
    }

    private void loadReceiptRealization() {
        upcomingReceiptCheques = new ArrayList<>();
        upcomingReceiptCheques = SERReminder.receiptRealization();
        DefaultTableModel dt = (DefaultTableModel) tblReceiptRealization.getModel();
        int i = 0;
        for (UpcomingCheque upcomingCheque : upcomingReceiptCheques) {
            dt.addRow(new Object[]{upcomingCheque.getCustomer(), upcomingCheque.getBank(), upcomingCheque.getDate(), upcomingCheque.getChequeNo(), upcomingCheque.getAmount()});
            i++;
        }
        for (int j = i; j < 13; j++) {
            dt.addRow(new Object[]{"", "", "", "", ""});

        }
        tblReceiptRealization.setDefaultRenderer(Object.class, new ReminderCellRender());
    }

    private void loadLowStock() {
        lowStockItems = new ArrayList<>();
        lowStockItems = SERReminder.lowStock();
        DefaultTableModel dt = (DefaultTableModel) tblLowSock.getModel();
        int i = 0;
        for (LowStockItem lowStockItem : lowStockItems) {
            dt.addRow(new Object[]{lowStockItem.getItem(), lowStockItem.getItemName(), lowStockItem.getDescription(), lowStockItem.getAvailable()});
            i++;
        }
        for (int j = i; j < 13; j++) {
            dt.addRow(new Object[]{"", "", "", ""});

        }
        tblLowSock.setDefaultRenderer(Object.class, new ReminderCellRender());
    }

    private void resetTable(JTable table) {
        int row = table.getRowCount();
        DefaultTableModel dt = (DefaultTableModel) table.getModel();
        for (int i = 0; i < row; i++) {
            dt.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initOthers() {
        resetTable(tblLowSock);
        resetTable(tblReceiptRealization);
        resetTable(tblVoucherRealization);
        loadVoucherRealization();
        loadReceiptRealization();
        loadLowStock();
        tblVoucherRealization.setShowHorizontalLines(false);
        tblReceiptRealization.setShowHorizontalLines(false);
        tblLowSock.setShowHorizontalLines(false);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucherRealization = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReceiptRealization = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLowSock = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtlogo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("Home");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/img/32 x 32/48px-Gnome-document-open-recent.svg.png"))); // NOI18N
        setLayer(-1);
        setOpaque(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setPreferredSize(new java.awt.Dimension(289, 260));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Up coming Payment Realization");
        jLabel1.setOpaque(true);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblVoucherRealization.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        tblVoucherRealization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vendore", "Bank Account", "Date", "Cheque No.", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoucherRealization.setGridColor(new java.awt.Color(102, 204, 255));
        tblVoucherRealization.setRowHeight(19);
        tblVoucherRealization.getTableHeader().setReorderingAllowed(false);
        tblVoucherRealization.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tblVoucherRealizationFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucherRealization);
        if (tblVoucherRealization.getColumnModel().getColumnCount() > 0) {
            tblVoucherRealization.getColumnModel().getColumn(0).setResizable(false);
            tblVoucherRealization.getColumnModel().getColumn(0).setPreferredWidth(160);
            tblVoucherRealization.getColumnModel().getColumn(1).setResizable(false);
            tblVoucherRealization.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblVoucherRealization.getColumnModel().getColumn(2).setResizable(false);
            tblVoucherRealization.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblVoucherRealization.getColumnModel().getColumn(3).setResizable(false);
            tblVoucherRealization.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblVoucherRealization.getColumnModel().getColumn(4).setResizable(false);
            tblVoucherRealization.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(289, 260));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblReceiptRealization.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        tblReceiptRealization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Customer", "Bank", "Date", "Cheque No.", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReceiptRealization.setGridColor(new java.awt.Color(102, 204, 255));
        tblReceiptRealization.setRowHeight(19);
        tblReceiptRealization.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblReceiptRealization);
        if (tblReceiptRealization.getColumnModel().getColumnCount() > 0) {
            tblReceiptRealization.getColumnModel().getColumn(0).setResizable(false);
            tblReceiptRealization.getColumnModel().getColumn(0).setPreferredWidth(160);
            tblReceiptRealization.getColumnModel().getColumn(1).setResizable(false);
            tblReceiptRealization.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblReceiptRealization.getColumnModel().getColumn(2).setResizable(false);
            tblReceiptRealization.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblReceiptRealization.getColumnModel().getColumn(3).setResizable(false);
            tblReceiptRealization.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblReceiptRealization.getColumnModel().getColumn(4).setResizable(false);
            tblReceiptRealization.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Up coming Receipt Realization");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Low Stock Items");
        jLabel2.setOpaque(true);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblLowSock.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        tblLowSock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item Code", "Name", "Description", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLowSock.setGridColor(new java.awt.Color(102, 204, 255));
        tblLowSock.setRowHeight(19);
        tblLowSock.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblLowSock);
        if (tblLowSock.getColumnModel().getColumnCount() > 0) {
            tblLowSock.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblLowSock.getColumnModel().getColumn(1).setPreferredWidth(160);
            tblLowSock.getColumnModel().getColumn(2).setPreferredWidth(75);
            tblLowSock.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setPreferredSize(new java.awt.Dimension(269, 130));

        txtlogo.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        txtlogo.setForeground(new java.awt.Color(179, 0, 0));
        txtlogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RAP-Logo small.png"))); // NOI18N
        txtlogo.setMaximumSize(new java.awt.Dimension(340, 128));
        txtlogo.setMinimumSize(new java.awt.Dimension(340, 128));
        txtlogo.setPreferredSize(new java.awt.Dimension(340, 128));
        txtlogo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtlogo, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setPreferredSize(new java.awt.Dimension(269, 130));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(5, 5, 5)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblVoucherRealizationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblVoucherRealizationFocusLost
        tblVoucherRealization.setFocusable(false);
    }//GEN-LAST:event_tblVoucherRealizationFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblLowSock;
    private javax.swing.JTable tblReceiptRealization;
    private javax.swing.JTable tblVoucherRealization;
    private javax.swing.JLabel txtlogo;
    // End of variables declaration//GEN-END:variables
    private ArrayList<UpcomingCheque> upcomingVoucherCheques;
    private ArrayList<UpcomingCheque> upcomingReceiptCheques;
    private ArrayList<LowStockItem> lowStockItems;

}
