/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system.masters.customer;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import mainApp.SERCommen;
import mainApp.findwindow.GUIFindWindow;
import sp_report.reg.SERInvoDetReport;
import system.accounts.transaction.receiptvoucher.againstinvoice.OBJInvoList;
import system.accounts.transaction.receiptvoucher.againstinvoice.SERInvoList;

/**
 *
 * @author RoWi
 */
public class GUIShowInvoices extends javax.swing.JFrame {

    /**
     * Creates new form GUIShowInvoices
     */
    public GUIShowInvoices(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
    }

    public GUIShowInvoices(Object object, boolean closable, Object valueAt) {
        this(null, closable);
        loadCust(valueAt.toString(), "AccCode");
        loadInvoice();
    }

    private void loadInvoice() {
        clrTable();
        String Cust = txtCustAccCode.getText();
        obji = SERInvoList.getList(Cust);
        int i = 1;
        DefaultTableModel dt = (DefaultTableModel) tblInvoice.getModel();
        for (OBJInvoList objq : obji) {
            dt.addRow(new Object[]{i, objq.getInvoNo(), objq.getInvoDate(), objq.getOriAmount(), objq.getPaiedAmount(), objq.getOwingAmount(), objq.getInvoBalance(), objq.getInstallAmount(), objq.getPayDate(), objq.getLoanNo(), objq.getStatus().equals("0") ? "PENDING" : "PAID"});
            i++;
        }

        calcAll();
    }

    private void clrTable() {
        DefaultTableModel df = (DefaultTableModel) tblInvoice.getModel();
        int rc = tblInvoice.getRowCount();
        for (int i = 0; i < rc; i++) {
            df.removeRow(0);
        }
    }

    private void calcAll() {
        DefaultTableModel df = (DefaultTableModel) tblInvoice.getModel();
        int rc = tblInvoice.getRowCount();

        double owi = 0.00, paid = 0.00, Bal = 0.00, adj = 0.00;

        for (int i = 0; i < rc; i++) {
            owi = owi + Double.parseDouble(df.getValueAt(i, 4).toString());
            paid = paid + Double.parseDouble(df.getValueAt(i, 5).toString());
            Bal = Bal + Double.parseDouble(df.getValueAt(i, 6).toString());
            adj = adj + Double.parseDouble(df.getValueAt(i, 7).toString());
        }
        txtTotOwing.setText(core.Locals.currencyFormat(owi));
        txtTotPaied.setText(core.Locals.currencyFormat(paid));
        txtTotInvoBalance.setText(core.Locals.currencyFormat(Bal));
        txtInstalAmount.setText(core.Locals.currencyFormat(adj));
    }

    private void loadCustomer() {
        new GUIFindWindow(null, true, "customer", "AccCode", "CustName").setVisible(true);
        String code = accountpackage.AccountPackage.CODE;
        txtCustAccCode.setText(accountpackage.AccountPackage.CODE);
        if (!code.equals("")) {
            txtCustCode.setText(SERCommen.getDescription("customer", "AccCode", accountpackage.AccountPackage.CODE, "CustCode"));
        }
        txtName.setText(accountpackage.AccountPackage.NAME);
//        serch(code);
        accountpackage.AccountPackage.CODE = "";
        accountpackage.AccountPackage.NAME = "";
    }

    private void loadCust(String cd, String fld) {
        txtName.setText(SERCommen.getDescription("customer", cd, fld, "PrintName"));
        txtCustAccCode.setText(SERCommen.getDescription("customer", cd, fld, "AccCode"));
        txtCustCode.setText(SERCommen.getDescription("customer", cd, fld, "CustCode"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoice = new javax.swing.JTable();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        txtCustCode = new javax.swing.JTextField();
        cmdCust = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtCustAccCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel14 = new javax.swing.JLabel();
        txtTotOwing = new javax.swing.JFormattedTextField();
        txtTotPaied = new javax.swing.JFormattedTextField();
        txtTotInvoBalance = new javax.swing.JFormattedTextField();
        txtInstalAmount = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Invoice");
        setResizable(false);

        tblInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "Invoice No", "Inv. Date", "Original Amt.", "Paied Amt.", "Amt. Owings", "Invoice Bal.", "Instal Amount", "PayDate", "Loan No", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInvoice.setGridColor(new java.awt.Color(204, 204, 204));
        tblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInvoiceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInvoice);
        if (tblInvoice.getColumnModel().getColumnCount() > 0) {
            tblInvoice.getColumnModel().getColumn(0).setResizable(false);
            tblInvoice.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        txtCustCode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCustCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustCodeActionPerformed(evt);
            }
        });
        jLayeredPane2.add(txtCustCode);
        txtCustCode.setBounds(320, 0, 70, 20);

        cmdCust.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tool bar/help.png"))); // NOI18N
        cmdCust.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmdCust.setContentAreaFilled(false);
        cmdCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCustActionPerformed(evt);
            }
        });
        jLayeredPane2.add(cmdCust);
        cmdCust.setBounds(70, 0, 20, 20);

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(255, 255, 241));
        txtName.setForeground(new java.awt.Color(153, 0, 0));
        txtName.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLayeredPane2.add(txtName);
        txtName.setBounds(90, 0, 230, 18);

        txtCustAccCode.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtCustAccCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustAccCodeActionPerformed(evt);
            }
        });
        jLayeredPane2.add(txtCustAccCode);
        txtCustAccCode.setBounds(0, 0, 70, 20);

        jLabel8.setText("Custo.  A/C");

        jLabel14.setBackground(new java.awt.Color(238, 238, 228));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Total");
        jLabel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel14.setOpaque(true);
        jLayeredPane1.add(jLabel14);
        jLabel14.setBounds(120, 0, 110, 20);

        txtTotOwing.setBackground(new java.awt.Color(204, 204, 255));
        txtTotOwing.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotOwing.setForeground(new java.awt.Color(153, 0, 0));
        txtTotOwing.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtTotOwing.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotOwing.setText("0.00");
        jLayeredPane1.add(txtTotOwing);
        txtTotOwing.setBounds(240, 0, 90, 20);

        txtTotPaied.setBackground(new java.awt.Color(204, 204, 255));
        txtTotPaied.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotPaied.setForeground(new java.awt.Color(153, 0, 0));
        txtTotPaied.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtTotPaied.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotPaied.setText("0.00");
        jLayeredPane1.add(txtTotPaied);
        txtTotPaied.setBounds(330, 0, 90, 20);

        txtTotInvoBalance.setBackground(new java.awt.Color(204, 204, 255));
        txtTotInvoBalance.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtTotInvoBalance.setForeground(new java.awt.Color(153, 0, 0));
        txtTotInvoBalance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtTotInvoBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotInvoBalance.setText("0.00");
        jLayeredPane1.add(txtTotInvoBalance);
        txtTotInvoBalance.setBounds(420, 0, 90, 20);

        txtInstalAmount.setBackground(new java.awt.Color(204, 204, 255));
        txtInstalAmount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtInstalAmount.setForeground(new java.awt.Color(153, 0, 0));
        txtInstalAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtInstalAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInstalAmount.setText("0.00");
        jLayeredPane1.add(txtInstalAmount);
        txtInstalAmount.setBounds(510, 0, 90, 20);

        jButton1.setText("Show Deponents");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLayeredPane2)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvoiceMouseClicked
        int clickCount = evt.getClickCount();
        int i = tblInvoice.getSelectedRowCount();
        if (i > 0) {
            jButton1.setEnabled(true);
        } else {
            jButton1.setEnabled(!true);
        }
        if (clickCount == 2) {
            showReport();
        }
    }//GEN-LAST:event_tblInvoiceMouseClicked

    private void txtCustCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustCodeActionPerformed
        loadCust(txtCustCode.getText(), "CustCode");
        loadInvoice();
    }//GEN-LAST:event_txtCustCodeActionPerformed

    private void cmdCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCustActionPerformed
        loadCustomer();
    }//GEN-LAST:event_cmdCustActionPerformed

    private void txtCustAccCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustAccCodeActionPerformed
        loadCust(txtCustAccCode.getText(), "AccCode");
        loadInvoice();
    }//GEN-LAST:event_txtCustAccCodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showDeponent();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCust;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInvoice;
    private javax.swing.JTextField txtCustAccCode;
    private javax.swing.JTextField txtCustCode;
    private javax.swing.JFormattedTextField txtInstalAmount;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtTotInvoBalance;
    private javax.swing.JFormattedTextField txtTotOwing;
    private javax.swing.JFormattedTextField txtTotPaied;
    // End of variables declaration//GEN-END:variables
    private ArrayList<OBJInvoList> obji;

    private void showReport() {
        int row = tblInvoice.getSelectedRow();
        String InvoNo = tblInvoice.getValueAt(row, 1).toString();
        try {
            SERInvoDetReport invoDetReport = new SERInvoDetReport(InvoNo, "INVONO", "REPCustomerInvoiceDetAll.jasper", "Customer Invoice Det. Invoice No. : " + InvoNo);
            invoDetReport.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GUIShowInvoices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void showDeponent() {
        int row = tblInvoice.getSelectedRow();
        String InvoNo = tblInvoice.getValueAt(row, 1).toString();
        try {
            SERInvoDetReport invoDetReport = new SERInvoDetReport(InvoNo, "INVONO", "REPDeponent.jasper", "Loan Deponents. Invoice No. : " + InvoNo);
            invoDetReport.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GUIShowInvoices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
